### ISSUE TITLE
Problem with new created file, pylint error code C0301 (Line too long)

### ISSUE THREAD

**Issue by Umekko** [SENATOROVAI/ml-chyngyz#9]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://t.me/c/1937296927/3602/25534) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) or [chatGPT](https://t.me/c/1937296927/2415/23729) and didn't find any helpful information.

### Attach a screenshot and write what did you do to fix the problem?

Attaching created file

[stash.JSON](https://github.com/user-attachments/files/17638671/stash.JSON)

### Error from the terminal / Code

HomeWork\stash.py:50:0: C0301: Line too long (211/79) (line-too-long)

### Expected behavior

Pylint should work properly and checker should be passed 

### Actual behavior

pre-commit error: 

HomeWork\stash.py:23:0: C0301: Line too long (255/79) (line-too-long)

**Comment by Nayil-Nord** [comment]
@Umekko 83fdfb03eacdb54b314019419296157d333fbc24

**Comment by Nayil-Nord** [comment]
https://github.com/SENATOROVAI/DataScience-Nayil/commit/83fdfb03eacdb54b314019419296157d333fbc24

![image](https://github.com/user-attachments/assets/eb0f170b-525c-4638-9e5f-45553f20c685)

**Comment by ruslansenatorov** [comment]
> ### Checklist
> 
>     * [x]  I added a descriptive title.
> 
>     * [x]  I searched through [existing issues](https://t.me/c/1937296927/3602/25534) and couldn't find a solution or duplicate issue.
> 
>     * [x]  I searched on the web (e.g. Google) or [chatGPT](https://t.me/c/1937296927/2415/23729) and didn't find any helpful information.
> 
> 
> ### Hash commit / link
> 
> _No response_
> ### Video
> 
> _No response_
> ### Attach a screenshot and write what did you do to fix the problem?
> 
> Attaching created file
> 
> [stash.JSON](https://github.com/user-attachments/files/17638671/stash.JSON)
> ### Error from the terminal / Code
> 
> HomeWork\stash.py:50:0: C0301: Line too long (211/79) (line-too-long)
> ### Expected behavior
> 
> Pylint should work properly and checker should be passed
> ### Actual behavior
> 
> pre-commit error:
> 
> HomeWork\stash.py:23:0: C0301: Line too long (255/79) (line-too-long)

ПОЧЕМУ JSON?

**Comment by ruslansenatorov** [comment]
[stash.JSON](https://github.com/user-attachments/files/17638671/stash.JSON)???

**Comment by ruslansenatorov** [comment]
ONLY ZIP

**Comment by Umekko** [comment]
> ONLY ZIP

Got it. Thank you. Further will link only ZIP files
